package routes

import (
	"github.com/labstack/echo"
	. "github.com/oldfritter/goDCE/api/v1"
)

func SetV1Interfaces(e *echo.Echo) {

	e.GET("/api/robot/v1/currencies", V1GetCurrencies)
	e.GET("/api/robot/v1/k", V1GetK)
	e.GET("/api/robot/v1/chart", V1GetChart)
	e.GET("/api/robot/v1/markets", V1GetMarkets)
	e.POST("/api/robot/v1/users/login", V1PostUsersLogin)
	e.GET("/api/robot/v1/users/me", V1GetUsersMe)
	e.GET("/api/robot/v1/users/accounts/:currency", V1GetUsersAccountsCurrency)
	e.GET("/api/robot/v1/users/accounts", V1GetUsersAccounts)
	e.GET("/api/robot/v1/depth", V1Getdepth)
	e.GET("/api/robot/v1/order", V1GetOrder)
	e.GET("/api/robot/v1/orders", V1GetOrders)
	e.POST("/api/robot/v1/orders", V1PostOrders)
	e.POST("/api/robot/v1/orders/multi2", V1PostOrdersMulti)
	e.POST("/api/robot/v1/order/delete", V1PostOrderDelete)
	e.POST("/api/robot/v1/orders/delete", V1PostOrdersDelete)
	e.POST("/api/robot/v1/orders/clear", V1PostOrdersClear)
	e.GET("/api/robot/v1/tickers", V1GetTickers)
	e.GET("/api/robot/v1/tickers/:market", V1GetTickersMarket)
	e.GET("/api/robot/v1/trades", V1GetTrades)
	e.GET("/api/robot/v1/trades/my", V1GetTradesMy)

	e.GET("/api/mobile/v1/currencies", V1GetCurrencies)
	e.GET("/api/mobile/v1/k", V1GetK)
	e.GET("/api/mobile/v1/chart", V1GetChart)
	e.GET("/api/mobile/v1/markets", V1GetMarkets)
	e.POST("/api/mobile/v1/users/login", V1PostUsersLogin)
	e.GET("/api/mobile/v1/users/me", V1GetUsersMe)
	e.GET("/api/mobile/v1/users/accounts/:currency", V1GetUsersAccountsCurrency)
	e.GET("/api/mobile/v1/users/accounts", V1GetUsersAccounts)
	e.GET("/api/mobile/v1/depth", V1Getdepth)
	e.GET("/api/mobile/v1/order", V1GetOrder)
	e.GET("/api/mobile/v1/orders", V1GetOrders)
	e.POST("/api/mobile/v1/orders", V1PostOrders)
	e.POST("/api/mobile/v1/orders/multi2", V1PostOrdersMulti)
	e.POST("/api/mobile/v1/order/delete", V1PostOrderDelete)
	e.POST("/api/mobile/v1/orders/delete", V1PostOrdersDelete)
	e.POST("/api/mobile/v1/orders/clear", V1PostOrdersClear)
	e.GET("/api/mobile/v1/tickers", V1GetTickers)
	e.GET("/api/mobile/v1/tickers/:market", V1GetTickersMarket)
	e.GET("/api/mobile/v1/trades", V1GetTrades)
	e.GET("/api/mobile/v1/trades/my", V1GetTradesMy)

	e.GET("/api/web/v1/currencies", V1GetCurrencies)
	e.GET("/api/web/v1/k", V1GetK)
	e.GET("/api/web/v1/chart", V1GetChart)
	e.GET("/api/web/v1/markets", V1GetMarkets)
	e.POST("/api/web/v1/users/login", V1PostUsersLogin)
	e.GET("/api/web/v1/users/me", V1GetUsersMe)
	e.GET("/api/web/v1/users/accounts/:currency", V1GetUsersAccountsCurrency)
	e.GET("/api/web/v1/users/accounts", V1GetUsersAccounts)
	e.GET("/api/web/v1/depth", V1Getdepth)
	e.GET("/api/web/v1/order", V1GetOrder)
	e.GET("/api/web/v1/orders", V1GetOrders)
	e.POST("/api/web/v1/orders", V1PostOrders)
	e.POST("/api/web/v1/orders/multi2", V1PostOrdersMulti)
	e.POST("/api/web/v1/order/delete", V1PostOrderDelete)
	e.POST("/api/web/v1/orders/delete", V1PostOrdersDelete)
	e.POST("/api/web/v1/orders/clear", V1PostOrdersClear)
	e.GET("/api/web/v1/tickers", V1GetTickers)
	e.GET("/api/web/v1/tickers/:market", V1GetTickersMarket)
	e.GET("/api/web/v1/trades", V1GetTrades)
	e.GET("/api/web/v1/trades/my", V1GetTradesMy)

}
